#pragma config(Sensor, S4,     HTSPB,          sensorI2CCustom9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/HTSPB-driver.h"
bool switchState =0;

task SwitchStatus()
{
	while(true)
	{
		int inputdata = HTSPBreadADC(HTSPB, 0, 10);
    bool SwitchState = (int)inputdata >512;
    writeDebugStreamLine("A0: %d", inputdata);
 	}
}

task main()
{

    startTask(SwitchStatus);
}
